services:
  - type: web
    name: scam-dunk-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://scam-dunk-production.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://scam-dunk-production.vercel.app,https://ocma.dev
      - key: LOG_LEVEL
        value: info
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false