version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - api_node_modules:/workspace/packages/api/node_modules
      - web_node_modules:/workspace/packages/web/node_modules
    command: sleep infinity
    network_mode: service:mongodb
    environment:
      - NODE_ENV=development
      - DANGEROUSLY_SKIP_PERMISSIONS=true
      - DATABASE_URL=mongodb://localhost:27017/scamdunk
      - REDIS_URL=redis://localhost:6379
      - JWT_SECRET=dev-secret-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-test-key}
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "6379:6379"
    environment:
      - MONGO_INITDB_DATABASE=scamdunk
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth --bind_ip_all

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    network_mode: service:mongodb
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
  node_modules:
  api_node_modules:
  web_node_modules: